spring.application.name=procrastinot
spring.datasource.url=jdbc:mysql://localhost:3306/procrastinot
spring.datasource.username=root
spring.datasource.password=GoLakers!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081
